# Verion of docker-compose to use 
version: "3"

services:
  ladbrary:
    build:
      context: . #Sets the directory for docker-compose to build.
    env_file:
      - .env
    # Maps port on the local machine to port on Docker image
    ports:
      - "8000:8000"
      
    volumes: 
    # Copy changes made to the project to your image in real-time.
      - .:/ladbrary
    # Handles the command used to run the project in the Docker container.
    command: 
      sh -c "python manage.py makemigrations"
      sh -c "python manage.py migrate"
      sh -c "python manage.py runserver 0.0.0.0:8000" 